// <auto-generated />
namespace DesignTinderWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _30032017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_30032017));
        
        string IMigrationMetadata.Id
        {
            get { return "201703300836135_30-03-2017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
